from typing import TypedDict, Optional, List, Dict


class CDSSGraphState(TypedDict):
    """MAC-inspired state schema for orchestrator-driven CDSS workflow
    
    The orchestrator (supervisor) maintains running_summary (compressed context) and routes to specialists.
    Full message history is tracked for comprehensive context, while specialists receive compressed summary.
    
    NOTE: EXAIM is passed via constructor injection, not state.
    """
    
    case_text: str
    """The clinical case input text"""
    
    messages: List[Dict[str, str]]
    """Full conversation history: [{role: str, name: str, content: str}, ...]
    Initialized with case presentation, then appends all agent outputs.
    Orchestrator sees full history (like MAC), specialists receive compressed summary."""
    
    running_summary: str
    """Orchestrator-maintained compressed summary of all findings so far (bounded context for specialists)"""
    
    recent_delta: str
    """Raw output from the most recent specialist (uncompressed)"""
    
    recent_agent: str
    """Name of the specialist who produced recent_delta (e.g., 'laboratory', 'cardiology')"""
    
    next_specialist_to_call: str
    """Next specialist to route to, or 'synthesis' to end. Set by orchestrator."""
    
    task_instruction: str
    """Specific task generated by orchestrator for the next specialist"""
    
    specialists_called: List[str]
    """List of specialists that have been called in this workflow"""
    
    iteration_count: int
    """Track number of turns to prevent infinite loops"""
    
    max_iterations: int
    """Maximum turns before forcing synthesis (MAC pattern: 13)"""
    
    final_synthesis: Optional[str]
    """Final synthesis from orchestrator combining all findings"""

