from typing import TypedDict, Optional, List


class CDSSGraphState(TypedDict):
    """Simplified state schema for orchestrator-driven CDSS workflow
    
    The orchestrator maintains running_summary (compressed context) and routes to specialists.
    Specialists receive: case + running_summary + recent_delta + recent_agent + task_instruction.
    
    NOTE: EXAID is no longer in state - agents receive EXAID reference via constructor injection.
    """
    
    case_text: str
    """The clinical case input text"""
    
    running_summary: str
    """Orchestrator-maintained compressed summary of all findings so far"""
    
    recent_delta: str
    """Raw output from the most recent specialist (uncompressed)"""
    
    recent_agent: str
    """Name of the specialist who produced recent_delta (e.g., 'laboratory', 'cardiology')"""
    
    next_specialist_to_call: str
    """Next specialist to route to, or 'synthesis' to end. Set by orchestrator."""
    
    task_instruction: str
    """Specific task generated by orchestrator for the next specialist"""
    
    specialists_called: List[str]
    """List of specialists that have been called in this workflow"""
    
    iteration_count: int
    """Track number of turns to prevent infinite loops"""
    
    max_iterations: int
    """Maximum turns before forcing synthesis (default: 20)"""
    
    final_synthesis: Optional[str]
    """Final synthesis from orchestrator combining all findings"""

